# Generated by Django 2.2.6 on 2022-07-11 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=250)),
                ('ingredientes', models.TextField()),
                ('moddo_preparo', models.TextField()),
                ('tempo_preparo', models.ImageField(upload_to='')),
                ('rendimento', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
                ('data_receita', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
