# Generated by Django 2.2.6 on 2022-07-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
